# -------------------------------------------------------- #
# EXPERIMENT PRELIMINARIES

- name: __experiment__ environment setup
  shell: |
    # cd into the skyhook-ceph build dir
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;

    # copy data
    wget {{ data_url }} ;

    # get expected results files
    bash get_expected.sh {{ test_id }} ;

    # compile the test driver
    make -j12 cls_tabular run-query ;

    # make the test pool
    rados mkpool {{ pool_name }} ;
    ceph osd pool set {{ pool_name }} size 1 ;

# -------------------------------------------------------- #
# WRITE THE TEST DATA TO CEPH

# DROP CACHES BEFORE WRITING!!!
- name: drop all osd caches
  shell: |
    ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
  with_inventory_hostnames:
    - osds

# WRITE TO CEPH
- name: __experiment__ write test data to ceph
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    yes | PATH=$PATH:bin ../src/progly/rados-store-glob.sh {{ pool_name }} {{ data_filename }} ;

# -------------------------------------------------------- #
# RUN TESTS:

#######################################################
# Q1 : select all
- name: __experiment__ Q1
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    bash "SELECT_ALL.sh" \
          {{ num_objs }} \
          {{ pool_name }} \
         "./{{ test_id }}_q1_match.txt" \
         "./{{ test_id }}_q1_time.txt" ;

- name: __experiment__ Q1 validate results match
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    python validate_match.py \
           "./{{ test_id }}_q1_match.txt" \
           "./expected_{{ test_id }}_q1_match.txt"  ;
##################################

#######################################################
# Q2 : select all with predicates
- name: __experiment__ Q2
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    bash "PRED_QUERY.sh" \
          {{ num_objs }} \
          {{ pool_name }} \
         "./{{ test_id }}_q2_match.txt" \
         "./{{ test_id }}_q2_time.txt" \
         "{{ select_preds2 }}" \
         "{{ project_cols2 }}" \
         "{{ data_schema }}" ;

- name: __experiment__ Q2 validate results match
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    python validate_match.py \
           "./{{ test_id }}_q2_match.txt" \
           "./expected_{{ test_id }}_q2_match.txt"  ;
##################################

#######################################################
# Q3 : select some with predicates
- name: __experiment__ Q3
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    bash "PRED_QUERY.sh" \
          {{ num_objs }} \
          {{ pool_name }} \
         "./{{ test_id }}_q3_match.txt" \
         "./{{ test_id }}_q3_time.txt" \
         "{{ select_preds3 }}" \
         "{{ project_cols3 }}" \
         "{{ data_schema }}" ;

- name: __experiment__ Q3 validate results match
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    python validate_match.py \
           "./{{ test_id }}_q3_match.txt" \
           "./expected_{{ test_id }}_q3_match.txt"  ;
##################################

#######################################################
# Q4 : sum
- name: __experiment__ Q4
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    bash "AGG_QUERY.sh" \
          {{ num_objs }} \
          {{ pool_name }} \
         "./{{ test_id }}_q4_match.txt" \
         "./{{ test_id }}_q4_time.txt" \
         "{{ select_preds4 }}" \
         "{{ table_name4 }}" \
         "{{ data_schema }}" ;

- name: __experiment__ Q4 validate results match
  shell: |
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    python validate_match.py \
           "./{{ test_id }}_q4_match.txt" \
           "./expected_{{ test_id }}_q4_match.txt"  ;
##################################
