# e.g. time ansible-playbook -K -b exps/arrangments_arity4.yml -vvvv ;

---
#- name: run setup_playbook to setup ceph cluster and setup skyhook.
#  import_playbook: ../setup_playbook.yml

# ------------------------------------- #
# EXPERIMENT : FBU Cols 4/cols 1mb
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    num_objs:         1
    format_device:    sda4
    data_filename:    skyhook.SFT_FLATBUF_UNION_ROW.obj.0-arity4-6rows
    exp_id :          orientation_designcosts_1mb
    pool_name:        paper_exps
    num_col_per_cols: 4
    test_id0:         fbucols_4per_1mb
    test_id1:         fbucols_2per_1mb
    test_id2:         fbucols_1per_1mb

    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"

  # ============================= #
  tasks:

    # -------------------------------------------------------- #
    # EXPERIMENT PRELIMINARIES

    - name: __experiment__ environment setup
      shell: |
        # cd into the skyhook-ceph build dir
        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;

        # copy data
        wget {{ data_url }} ;

        # compile the test driver
        make -j12 cls_tabular run-query fbwriter_fbu

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

    # -------------------------------------------------------- #
    # WRITE THE TEST DATA TO CEPH

    # DROP CACHES BEFORE WRITING!!!
    - name: drop all osd caches
      shell: |
        ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
      with_inventory_hostnames:
        - osds

    # FBU_Cols arity-3 1mb (50,000 rows) => obj.0
    - name: __experiment__ write test data to ceph
      shell: |
        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
        yes | PATH=$PATH:bin ../src/progly/rados-store-glob.sh {{ pool_name }} {{ data_filename }} ;

    # -------------------------------------------------------- #
    # run tests:

    #######################################################
    # Q1 : select all
    - name: __experiment__ Q1
      shell: |
        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
        bash "{{ test_id0 }}_q1.sh" \
              {{ num_objs }} \
              {{ pool_name }} \
             "./{{ test_id0 }}_q1_match.txt" \
             "./{{ test_id0 }}_q1_time.txt" ;

    - name: __experiment__ Q1 validate results match
      shell: |
        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
        python validate_match.py \
               "./{{ test_id0 }}_q1_match.txt" \
               "./expected_{{ test_id0 }}_q1_match.txt"  ;
    ##################################

    #######################################################
#    # Q2 : select all with predicates
#    - name: __experiment__ Q2
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        { time bin/run-query \
#                 --num-objs 1 \
#                 --pool {{ pool_name }} \
#                 --wthreads 1 \
#                 --qdepth 10 \
#                 --query flatbuf \
#                 --select "att0,lt,25;att1,lt,25.0;"  \
#                 --project-cols att0,att1,att2,att3 \
#                 --data-schema "0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ; 3 8 0 0 ATT3 ;" \
#          > "blah_q2_match.txt" ; } \
#        2>> "blah_q2_time.txt" ;
#        #  > "{{result_dir_path }}/{{ test_id0 }}_q2_match.txt" ; }
#        #2>> "{{result_dir_path }}/{{ test_id0 }}_q2_time.txt" ;
#
#    # Q3 : select two with predicates
#    - name: __experiment__ Q3
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        { time bin/run-query \
#                 --num-objs 1 \
#                 --pool {{ pool_name }} \
#                 --wthreads 1 \
#                 --qdepth 10 \
#                 --query flatbuf \
#                 --select "att0,lt,25;att1,lt,25.0;"  \
#                 --project-cols att0,att2 \
#                 --data-schema "0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ; 3 8 0 0 ATT3 ;" \
#          > "blah_q3_match.txt" ; } \
#        2>> "blah_q3_time.txt" ;
#        #  > "{{result_dir_path }}/{{ test_id0 }}_q3_match.txt" ; }
#        #2>> "{{result_dir_path }}/{{ test_id0 }}_q3_time.txt" ;
#
#    # Q4 : sum on att0
#    - name: __experiment__ Q4
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        { time bin/run-query \
#                 --num-objs 1 \
#                 --pool {{ pool_name }} \
#                 --wthreads 1 \
#                 --qdepth 10 \
#                 --query flatbuf \
#                 --select-preds ";att0,sum,0;" \
#                 --table-name "atable" \
#                 --data-schema "0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ; 3 8 0 0 ATT3 ;" \
#          > "blah_q4_match.txt" ; } \
#        2>> "blah_q4_time.txt" ;
#        #  > "{{result_dir_path }}/{{ test_id0 }}_q4_match.txt" ; }
#        #2>> "{{result_dir_path }}/{{ test_id0 }}_q4_time.txt" ;

# ------------------------------------- #
# SELF_VALIDATION ON TIME FILES
# ------------------------------------- #
#- hosts: clients
#  # ============================= #
#  vars:
#    # input vars
#    test_id0_1mb: fbucols_4per_1mb
#    test_id1_1mb: fbucols_2per_1mb
#    test_id2_1mb: fbucols_1per_1mb
#
#    test_id0_10mb: fbucols_4per_10mb
#    test_id1_10mb: fbucols_2per_10mb
#    test_id2_10mb: fbucols_1per_10mb
#
#    test_id0_100mb: fbucols_4per_100mb
#    test_id1_100mb: fbucols_2per_100mb
#    test_id2_100mb: fbucols_1per_100mb
#
#  # ============================= #
#  tasks:
#
     ###########################################################
     # fbucols_4per
     ###########################################################
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q1 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q1_time.txt" \
#               "./{{ test_id0_10mb }}_q1_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q1_time.txt" \
#               "./{{ test_id0_100mb }}_q1_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q2 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q2_time.txt" \
#               "./{{ test_id0_10mb }}_q2_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q2_time.txt" \
#               "./{{ test_id0_100mb }}_q2_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q3 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q3_time.txt" \
#               "./{{ test_id0_10mb }}_q3_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q3_time.txt" \
#               "./{{ test_id0_100mb }}_q3_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q4 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q4_time.txt" \
#               "./{{ test_id0_10mb }}_q4_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q4_time.txt" \
#               "./{{ test_id0_100mb }}_q4_time.txt"  ;

     ###########################################################
     # fbucols_2per
     ###########################################################
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q1 validate time asserts fbucols_2per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id1_1mb }}_q1_time.txt" \
#               "./{{ test_id1_10mb }}_q1_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id1_10mb }}_q1_time.txt" \
#               "./{{ test_id1_100mb }}_q1_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q2 validate time asserts fbucols_2per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id1_1mb }}_q2_time.txt" \
#               "./{{ test_id1_10mb }}_q2_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id1_10mb }}_q2_time.txt" \
#               "./{{ test_id1_100mb }}_q2_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q3 validate time asserts fbucols_2per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id1_1mb }}_q3_time.txt" \
#               "./{{ test_id1_10mb }}_q3_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id1_10mb }}_q3_time.txt" \
#               "./{{ test_id1_100mb }}_q3_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q4 validate time asserts fbucols_2per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id1_1mb }}_q4_time.txt" \
#               "./{{ test_id1_10mb }}_q4_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id1_10mb }}_q4_time.txt" \
#               "./{{ test_id1_100mb }}_q4_time.txt"  ;

     ###########################################################
     # fbucols_1per
     ###########################################################
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q1 validate time asserts fbucols_1per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id2_1mb }}_q1_time.txt" \
#               "./{{ test_id2_10mb }}_q1_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id2_10mb }}_q1_time.txt" \
#               "./{{ test_id2_100mb }}_q1_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q2 validate time asserts fbucols_1per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id2_1mb }}_q2_time.txt" \
#               "./{{ test_id2_10mb }}_q2_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id2_10mb }}_q2_time.txt" \
#               "./{{ test_id2_100mb }}_q2_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q3 validate time asserts fbucols_1per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id2_1mb }}_q3_time.txt" \
#               "./{{ test_id2_10mb }}_q3_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id2_10mb }}_q3_time.txt" \
#               "./{{ test_id2_100mb }}_q3_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q4 validate time asserts fbucols_1per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id2_1mb }}_q4_time.txt" \
#               "./{{ test_id2_10mb }}_q4_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id2_10mb }}_q4_time.txt" \
#               "./{{ test_id2_100mb }}_q4_time.txt"  ;
