# -------------------------------------------------------- #
# EXPERIMENT PRELIMINARIES

# DROP CACHES BEFORE WRITING!!!
- name: drop all osd caches
  shell: |
    ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
  with_inventory_hostnames:
    - osds

- name: __experiment__ environment setup
  shell: |
    # cd into the skyhook-ceph build dir
    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;

    # make sure no objects exist in the pool
    bash clear_objs.sh {{ pool_name }} ;

    # make the test pool
    ceph osd pool delete {{ pool_name }} ;
    ceph osd pool delete {{ pool_name }} {{ pool_name }} --yes-i-really-mean-it ;
    rados mkpool {{ pool_name }} ;
    ceph osd pool set {{ pool_name }} size 1 ;
    ceph osd pool set {{ pool_name }} pg_num 128 ;

    # copy data and untar
    python scp_and_write_data.py \
                 {{ this_user }} \
                 {{ data_node_addr }} \
                 {{ data_path }} \
                 {{ data_dir }} \
                 {{ format_secondary_device }} \
                 {{ pool_name }} ;

    # get expected results files
    #bash get_expected.sh {{ test_id }} ;

    # compile the test driver
    make -j12 cls_tabular run-query ;

# -------------------------------------------------------- #
# RUN TESTS:

    ########################################################
    ## Q0 : selectivity att0 1%
    #- name: __experiment__ Q0 selectivity att0 1-percent
    #  shell: |
    #    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
    #        bash "PRED_QUERY.sh" \
    #              {{ num_objs }} \
    #              {{ pool_name }} \
    #             "./{{ test_id }}_q0_match.txt" \
    #             "./{{ test_id }}_q0_time.txt" \
    #             {{ select_preds0 }} \
    #             {{ project_cols0 }} \
    #             {{ data_schema0 }} \
    #             {{ use_cls }};

#- name: __experiment__ Q0 validate results match
#  shell: |
#    cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#    python validate_match.py \
#           "./{{ test_id }}_q0_match.txt" \
#           "./expected_{{ test_id }}_q0_match.txt"  ;
##################################
