# e.g. time ansible-playbook -K -b exps/orientations_pdsw19.yml -vvvv ;

---
#- name: run setup_playbook to setup ceph cluster and setup skyhook.
#  import_playbook: ../setup_playbook.yml

# ------------------------------------- #
# EXPERIMENT : FBX Rows 
#              arity3 100 x 10mb objects
# ------------------------------------- #
- hosts: clients
  # ============================= #
  vars_files:
    - ../vars/install_vars_luminous_sda4.yml
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"

    # input vars
    num_objs:         100
    format_device:    sda4
    pool_name:        test_exps
    num_col_per_cols: 4 
    test_id:          orientations_fbxrows_arity3_10mb_100objs
    use_cls:          true

    select_preds0: "\"att0,leq,10;\""
    project_cols0: "att0"
    data_schema0: "\"0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ;\""

    data_node_addr:   "128.105.144.251"
    data_path:        "/mnt/sda4/arity3datasets/flatflex/"
    data_dir:         "fbxrows-arity3-10mb-100objs"
    data_file_prefix: "fbmeta.Skyhook.v2.SFT_FLATBUF_FLEX_ROW.{{ data_dir }}."
    data_file_suffix: ".1-1"
  # ============================= #
  tasks:
  - import_tasks: exp_helper_selectivity.yml

# ------------------------------------- #
# EXPERIMENT : FBU Rows 
#              arity3 100 x 10mb objects
# ------------------------------------- #
- hosts: clients
  # ============================= #
  vars_files:
    - ../vars/install_vars_luminous_sda4.yml
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"

    # input vars
    num_objs:         100
    format_device:    sda4
    pool_name:        test_exps
    num_col_per_cols: 4 
    test_id:          orientations_fburows_arity3_10mb_100objs
    use_cls:          true

    select_preds0: "\"att0,leq,10;\""
    project_cols0: "att0"
    data_schema0: "\"0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ;\""

    data_node_addr:   "128.105.144.251"
    data_path:        "/mnt/sda4/arity3datasets/fburows/"
    data_dir:         "fburows-arity3-10mb-100objs"
    data_file_prefix: "skyhook.SFT_FLATBUF_UNION_ROW.{{ data_dir }}."
    data_file_suffix: "NONE"
  # ============================= #
  tasks:
  - import_tasks: exp_helper_selectivity.yml

# ------------------------------------- #
# EXPERIMENT : FBU Cols 
#              arity3 100 x 10mb objects
# ------------------------------------- #
- hosts: clients
  # ============================= #
  vars_files:
    - ../vars/install_vars_luminous_sda4.yml
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"

    # input vars
    num_objs:         100
    format_device:    sda4
    pool_name:        test_exps
    num_col_per_cols: 4 
    test_id:          orientations_fbucols4_arity3_10mb_100objs
    use_cls:          true

    select_preds0: "\"att0,leq,10;\""
    project_cols0: "att0"
    data_schema0: "\"0 7 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ;\""

    data_node_addr:   "128.105.144.251"
    data_path:        "/mnt/sda4/arity3datasets/fbucols/"
    data_dir:         "fbucols4-arity3-10mb-100objs"
    data_file_prefix: "skyhook.SFT_FLATBUF_UNION_COL.{{ data_dir }}."
    data_file_suffix: "NONE"
  # ============================= #
  tasks:
  - import_tasks: exp_helper_selectivity.yml

# ------------------------------------- #
# SELF_VALIDATION ON TIME FILES
# ------------------------------------- #
#- hosts: clients
#  # ============================= #
#  vars:
#    # input vars
#    test_id0_1mb: fbucols_4per_1mb
#    test_id1_1mb: fbucols_2per_1mb
#    test_id2_1mb: fbucols_1per_1mb
#
#    test_id0_10mb: fbucols_4per_10mb
#    test_id1_10mb: fbucols_2per_10mb
#    test_id2_10mb: fbucols_1per_10mb
#
#    test_id0_100mb: fbucols_4per_100mb
#    test_id1_100mb: fbucols_2per_100mb
#    test_id2_100mb: fbucols_1per_100mb
#
#  # ============================= #
#  tasks:
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q1 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q1_time.txt" \
#               "./{{ test_id0_10mb }}_q1_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q1_time.txt" \
#               "./{{ test_id0_100mb }}_q1_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q2 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q2_time.txt" \
#               "./{{ test_id0_10mb }}_q2_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q2_time.txt" \
#               "./{{ test_id0_100mb }}_q2_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q3 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q3_time.txt" \
#               "./{{ test_id0_10mb }}_q3_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q3_time.txt" \
#               "./{{ test_id0_100mb }}_q3_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q4 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q4_time.txt" \
#               "./{{ test_id0_10mb }}_q4_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q4_time.txt" \
#               "./{{ test_id0_100mb }}_q4_time.txt"  ;
