# e.g. time ansible-playbook -K -b exps/orientations_arity4_6rows.yml -vvvv ;

---
#- name: run setup_playbook to setup ceph cluster and setup skyhook.
#  import_playbook: ../setup_playbook.yml

# ------------------------------------- #
# EXPERIMENT : FBU Rows example
# ------------------------------------- #
- hosts: clients
  # ============================= #
  vars:
    # input vars
    num_objs:         1
    format_device:    sda4
    data_filename:    skyhook.SFT_FLATBUF_UNION_ROW.obj.0-arity4-6rows
    pool_name:        test_exps
    num_col_per_cols: 4 
    test_id:          orientations_arity4_6rows_fburows

    data_schema: "0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ; 3 8 0 0 ATT3 ;"

    select_preds2: "att0,lt,25;att1,lt,25.0;"
    project_cols2: "att0,att1,att2,att3"

    select_preds3: "att0,lt,25;att1,lt,25.0;"
    project_cols3: "att0,att2"

    select_preds4: ";att0,sum,0;"
    table_name4:   "atable"
    
    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"

  # ============================= #
  tasks:
  - import_tasks: exp_helper.yml

# ------------------------------------- #
# EXPERIMENT : FBU Cols example
# ------------------------------------- #
- hosts: clients
  # ============================= #
  vars:
    # input vars
    num_objs:         1
    format_device:    sda4
    data_filename:    skyhook.SFT_FLATBUF_UNION_COL.obj.0-arity4-6rows-fbucols-4per
    pool_name:        test_exps
    num_col_per_cols: 4 
    test_id:          orientations_arity4_6rows_fbucols_4per

    data_schema: "0 8 0 0 ATT0 ; 1 12 0 0 ATT1 ; 2 15 0 0 ATT2 ; 3 8 0 0 ATT3 ;"

    select_preds2: "att0,lt,25;att1,lt,25.0;"
    project_cols2: "att0,att1,att2,att3"

    select_preds3: "att0,lt,25;att1,lt,25.0;"
    project_cols3: "att0,att2"

    select_preds4: ";att0,sum,0;"
    table_name4:   "atable"
    
    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"

  # ============================= #
  tasks:
  - import_tasks: exp_helper.yml

# ------------------------------------- #
# SELF_VALIDATION ON TIME FILES
# ------------------------------------- #
#- hosts: clients
#  # ============================= #
#  vars:
#    # input vars
#    test_id0_1mb: fbucols_4per_1mb
#    test_id1_1mb: fbucols_2per_1mb
#    test_id2_1mb: fbucols_1per_1mb
#
#    test_id0_10mb: fbucols_4per_10mb
#    test_id1_10mb: fbucols_2per_10mb
#    test_id2_10mb: fbucols_1per_10mb
#
#    test_id0_100mb: fbucols_4per_100mb
#    test_id1_100mb: fbucols_2per_100mb
#    test_id2_100mb: fbucols_1per_100mb
#
#  # ============================= #
#  tasks:
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q1 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q1_time.txt" \
#               "./{{ test_id0_10mb }}_q1_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q1_time.txt" \
#               "./{{ test_id0_100mb }}_q1_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q2 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q2_time.txt" \
#               "./{{ test_id0_10mb }}_q2_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q2_time.txt" \
#               "./{{ test_id0_100mb }}_q2_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q3 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q3_time.txt" \
#               "./{{ test_id0_10mb }}_q3_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q3_time.txt" \
#               "./{{ test_id0_100mb }}_q3_time.txt"  ;
#
#    # -------------------------------------------------------- #
#    - name: __experiment__ Q4 validate time asserts fbucols_4per
#      shell: |
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        python validate_time_assert.py \
#               "./{{ test_id0_1mb }}_q4_time.txt" \
#               "./{{ test_id0_10mb }}_q4_time.txt"  ;
#        python validate_time_assert.py \
#               "./{{ test_id0_10mb }}_q4_time.txt" \
#               "./{{ test_id0_100mb }}_q4_time.txt"  ;
