# e.g. ansible-playbook -K -b exps/run-papertests.yml -vvvv --extra-vars "data_file=params/raw_1mb.yml" ;

# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/skyhook.SFT_FLATBUF_UNION_COL.obj.0
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/skyhook.SFT_FLATBUF_UNION_ROW.obj.0
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/fbmeta.Skyhook.v2.SFT_FLATBUF_FLEX_ROW.arity1_paper_exps.0.1-1
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/concat-data.txt
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/separate-data.txt

---
#- name: run setup_playbook to setup ceph cluster
#  import_playbook: ../setup_playbook.yml

# ------------------------------------- #
# EXPERIMENT : concat-data, sum
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    format_device: sda4
    data_filename: concat-data.txt
    test_id:       concat-data-sum
    pool_name:     paper_exps
    test_type:     0
    obj_name:      "{{ test_id }}"
    optype:        sum
    driver_name:   run-papertests

    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    result_dir_path: "./res_{{ test_id }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/"

  # ============================= #
  tasks:
    - name: drop all osd caches
      shell: |
        ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
      with_inventory_hostnames:
        - osds

    - name: "__experiment__ {{ test_id }}"
      shell: |
        # cd into the skyhookdm-ceph build dir
        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;

        # copy data
        wget {{ data_url }} ;

        # make results dir
        mkdir {{ result_dir_path  }} ;

        # compile the test driver
        make -j12 {{ driver_name }} run-query ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # run the test
        time bash run-papertests-driver.sh {{ result_dir_path }} {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} > "res_{{ obj_name }}_time.txt" ;

# ------------------------------------- #
# EXPERIMENT : concat-data, randomsearch
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    format_device: sda4
    data_filename: concat-data.txt
    test_id:       concat-data-randomsearch
    pool_name:     paper_exps
    test_type:     0
    obj_name:      "{{ test_id }}"
    optype:        randomsearch
    driver_name:   run-papertests

    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    result_dir_path: "./res_{{ test_id }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/"

  # ============================= #
  tasks:
    - name: drop all osd caches
      shell: |
        ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
      with_inventory_hostnames:
        - osds

    - name: "__experiment__ {{ test_id }}"
      shell: |
        # cd into the skyhookdm-ceph build dir
        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;

        # copy data
        wget {{ data_url }} ;

        # make results dir
        mkdir {{ result_dir_path  }} ;

        # compile the test driver
        make -j12 {{ driver_name }} run-query ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # run the test
        time bash run-papertests-driver.sh {{ result_dir_path }} {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} > "res_{{ obj_name }}_time.txt" ;

# ------------------------------------- #
# EXPERIMENT : separate-data, sum
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    format_device: sda4
    data_filename: separate-data.txt
    test_id:       separate-data-sum
    pool_name:     paper_exps
    test_type:     0
    obj_name:      "{{ test_id }}"
    optype:        sum
    driver_name:   run-papertests

    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    result_dir_path: "./res_{{ test_id }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/"

  # ============================= #
  tasks:
    - name: drop all osd caches
      shell: |
        ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
      with_inventory_hostnames:
        - osds

    - name: "__experiment__ {{ test_id }}"
      shell: |
        # cd into the skyhookdm-ceph build dir
        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;

        # copy data
        wget {{ data_url }} ;

        # make results dir
        mkdir {{ result_dir_path  }} ;

        # compile the test driver
        make -j12 {{ driver_name }} run-query ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # run the test
        time bash run-papertests-driver.sh {{ result_dir_path }} {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} > "res_{{ obj_name }}_time.txt" ;


# ------------------------------------- #
# EXPERIMENT : separate-data, randomsearch
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    format_device: sda4
    data_filename: separate-data.txt
    test_id:       separate-data-randomsearch
    pool_name:     paper_exps
    test_type:     0
    obj_name:      "{{ test_id }}"
    optype:        sum
    driver_name:   run-papertests

    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    result_dir_path: "./res_{{ test_id }}"
    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/"

  # ============================= #
  tasks:
    - name: drop all osd caches
      shell: |
        ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
      with_inventory_hostnames:
        - osds

    - name: "__experiment__ {{ test_id }}"
      shell: |
        # cd into the skyhookdm-ceph build dir
        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;

        # copy data
        wget {{ data_url }} ;

        # make results dir
        mkdir {{ result_dir_path  }} ;

        # compile the test driver
        make -j12 {{ driver_name }} run-query ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # run the test
        time bash run-papertests-driver.sh {{ result_dir_path }} {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} > "res_{{ obj_name }}_time.txt" ;

