# e.g. ansible-playbook -K -b exps/run-papertests.yml -vvvv --extra-vars "data_file=params/raw_1mb.yml" ;

# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/skyhook.SFT_FLATBUF_UNION_COL.obj.0
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/skyhook.SFT_FLATBUF_UNION_ROW.obj.0
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/fbmeta.Skyhook.v2.SFT_FLATBUF_FLEX_ROW.arity1_paper_exps.0.1-1
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/concat-data.txt
# https://users.soe.ucsc.edu/~kdahlgren/pdsw19/separate-data.txt

---
#- name: run setup_playbook to setup ceph cluster
#  import_playbook: ../setup_playbook.yml

# ------------------------------------- #
# EXPERIMENT : concat-data, sum
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: concat-data.txt
#    test_id:       concat-data-sum
#    pool_name:     paper_exps
#    test_type:     0
#    obj_name:      "{{ test_id }}"
#    optype:        sum
#
#    # derived vars
#    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-papertests run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ test_id }} {{ data_filename }} ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash run-papertests-driver.sh "res_{{ obj_name }}_match.txt" {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} ;

# ------------------------------------- #
# EXPERIMENT : concat-data, randomsearch
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: concat-data.txt
#    test_id:       concat-data-randomsearch
#    pool_name:     paper_exps
#    test_type:     0
#    obj_name:      "{{ test_id }}"
#    optype:        randomsearch
#
#    # derived vars
#    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-papertests run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ test_id }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash run-papertests-driver.sh "res_{{ obj_name }}_match.txt" {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} ;

# ------------------------------------- #
# EXPERIMENT : separate-data, sum
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: separate-data.txt
#    test_id:       separate-data-sum
#    pool_name:     paper_exps
#    test_type:     1
#    obj_name:      "{{ test_id }}"
#    optype:        sum
#
#    # derived vars
#    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-papertests run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ test_id }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash run-papertests-driver.sh "res_{{ obj_name }}_match.txt" {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} ;

# ------------------------------------- #
# EXPERIMENT : separate-data, randomsearch
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: separate-data.txt
#    test_id:       separate-data-randomsearch
#    pool_name:     paper_exps
#    test_type:     1
#    obj_name:      "{{ test_id }}"
#    optype:        sum
#
#    # derived vars
#    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:        "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-papertests run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ test_id }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash run-papertests-driver.sh "res_{{ obj_name }}_match.txt" {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} ;

# ------------------------------------- #
# EXPERIMENT : fbxrows, sum
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: fbmeta.Skyhook.v2.SFT_FLATBUF_FLEX_ROW.arity1_paper_exps.0.1-1
#    test_id:       fbxrows-sum
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ test_id }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : fbxrows, randomsearch
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: fbmeta.Skyhook.v2.SFT_FLATBUF_FLEX_ROW.arity1_paper_exps.0.1-1
#    test_id:       fbxrows-randomsearch
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver_randomsearch.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : fburows, sum
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: skyhook.SFT_FLATBUF_UNION_ROW.obj.0
#    test_id:       fburows-sum
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : fburows, randomsearch
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: skyhook.SFT_FLATBUF_UNION_ROW.obj.0
#    test_id:       fburows-randomsearch
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver_randomsearch.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : fbucols, sum
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: skyhook.SFT_FLATBUF_UNION_COL.obj.0
#    test_id:       fbucols-sum
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : fbucols, randomsearch
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    format_device: sda4
    data_filename: skyhook.SFT_FLATBUF_UNION_COL.obj.0
    test_id:       fbucols-randomsearch
    pool_name:     paper_exps
    obj_name:      obj.0
    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"

  # ============================= #
  tasks:
    - name: "__experiment__ {{ test_id }} 0"
      shell: |
        # cd into the skyhookdm-ceph build dir
        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # make sure no objects exist in the pool
        bash clear_objs.sh {{ pool_name }} ;

        # copy data
        wget {{ data_url }} ;

        # compile the test driver
        make -j12 run-query ;

        # write data
        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;

    - name: "__experiment__ {{ test_id }} 1"
      shell: |
        # cd into the skyhookdm-ceph build dir
        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
        # run the test
        bash papertests-run-query-driver_randomsearch.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : arrow, sum
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: skyhook.SFT_ARROW.arity1_paper_exps.0
#    test_id:       arrow-sum
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver.sh {{ pool_name }} {{ test_id }} ;

# ------------------------------------- #
# EXPERIMENT : arrow, randomsearch
# ------------------------------------- #
#- hosts: clients
#
#  # ============================= #
#  vars:
#    # input vars
#    format_device: sda4
#    data_filename: skyhook.SFT_ARROW.arity1_paper_exps.0
#    test_id:       arrow-randomsearch
#    pool_name:     paper_exps
#    obj_name:      obj.0
#    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
#    data_url:      "https://users.soe.ucsc.edu/~kdahlgren/pdsw19/{{ data_filename }}"
#
#  # ============================= #
#  tasks:
#    - name: "__experiment__ {{ test_id }} 0"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#
#        # make the test pool
#        rados mkpool {{ pool_name }} ;
#        ceph osd pool set {{ pool_name }} size 1 ;
#
#        # make sure no objects exist in the pool
#        bash clear_objs.sh {{ pool_name }} ;
#
#        # copy data
#        wget {{ data_url }} ;
#
#        # compile the test driver
#        make -j12 run-query ;
#
#        # write data
#        rados -p {{ pool_name }} put {{ obj_name }} {{ data_filename }} ;
#
#    - name: "__experiment__ {{ test_id }} 1"
#      shell: |
#        # cd into the skyhookdm-ceph build dir
#        cd "/mnt/{{ format_device }}/skyhookdm-ceph/build" ;
#        # run the test
#        bash papertests-run-query-driver_randomsearch.sh {{ pool_name }} {{ test_id }} ;
