# e.g. ansible-playbook -K -b exps/run-papertests.yml -vvvv --extra-vars "data_file=params/raw_1mb.yml" ;

---
- name: run setup_playbook to setup ceph cluster
  import_playbook: ../setup_playbook.yml

# ------------------------------------- #
# EXPERIMENT : raw 1mb, sum
# ------------------------------------- #
- hosts: clients

  # ============================= #
  vars:
    # input vars
    format_device: sda4
    data_filename: dataset_case1_1mb.txt
    test_id:       raw_1mb
    pool_name:     paper_exps
    test_type:     0
    obj_name:      test0
    optype:        sum
    driver_name:   run-papertests

    # derived vars
    curr_datetime:   "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    result_dir_path: "./res_{{ test_id }}"
    data_url:        "https://users.soe.ucsc.edu/~kmdahlgr/pdsw19/testdata/{{ data_filename }}"

  # ============================= #
  tasks:
    - name: drop all osd caches
      shell: |
        ssh {{ item }} "echo 1 | sudo tee /proc/sys/vm/drop_caches" ;
      with_inventory_hostnames:
        - osds

    - name: __experiment__ raw 1mb
      shell: |
        # cd into the skyhook-ceph build dir
        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;

        # copy data
        wget {{ data_url }} ;

        # make results dir
        mkdir {{ result_dir_name  }} ;

        # compile the test driver
        make -j12 {{ driver_name }} ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # run the test
        bin/run-papertests {{ data_filename }} {{ result_dir_path }} {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} ;
