---
# e.g. ansible-playbook -K -b exps/run-papertests.yml -vvvv --extra-vars "data_file=params/raw_1mb.yml" ;

# always setup ceph first.
- import_playbook: ../setup_playbook.yml

# then run the experiment from the client skyhook-ceph repo
- hosts: clients
  vars:
    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
  vars_files:
    - "{{ data_file }}"
  tasks:
    - name: "test paper_exps"
      shell: |

        # cd into the skyhook-ceph build dir
        cd "/mnt/{{ format_device }}/skyhook-ceph/build" ;

        # compile the test driver
        make -j12 run-papertests ;

        # make the test pool
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;

        # run the test
        bin/run-papertests {{ data_path }} {{ res_path }}/res_{{ curr_datetime }}.txt {{ pool_name }} {{ test_type }} {{ obj_name }} {{ optype }} ;

#    - name: "self-validation"
#        shell: |
#          echo "self-validate here!!!" ;
