---
- import_playbook: ../setup_playbook.yml

- hosts: clients
  vars:
    curr_datetime: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
  vars_files:
    - "params/{{ data_file }}"
  tasks:
    - name: "test paper_exps"
      shell: |
        cd /mnt/sda4/skyhook-ceph/build ;
        rados mkpool {{ pool_name }} ;
        ceph osd pool set {{ pool_name }} size 1 ;
        bin/run-papertests {{ data_path }} {{ res_path }}/res_{{ curr_datetime }}.txt {{ pool_name }} {{ test_type }} {{ obj_name }} ;
      tags:
        - exp_only
