- name: "set non-interactive"
  shell: |
    echo "DEBIAN_FRONTEND=noninteractive" >> "{{ local_home }}/.profile" ;
    source "{{ local_home }}/.profile" ;

- name: "installing software"
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - tmux
