# e.g. time ansible-playbook -K -b setup_playbook.yml -vvvv ;

---
- name: run setup ceph cluster playbook from lib/ceph-deploy-ansible
  import_playbook: lib/ceph-deploy-ansible/ansible/playbook.yml

- hosts: clients
  tasks:
    - name: "install postgres on client0"
      become: yes
      shell: |
        sudo su -c "useradd postgres" ;
        sudo su -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >  /etc/apt/sources.list.d/pgdg.list' ;
        sudo su -c "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -" ;
        sudo su -c "sudo apt-get update" ;
        sudo su -c "yes | apt-get install postgresql-10" ;
        sudo su -c "yes | apt-get install postgresql-server-dev-10" ;
        sudo su -c "yes | apt-get install postgresql-contrib" ;

# clone skyhook on each node, 
# run install-deps, 
# make the source code, 
# install the generated tabular so.
- hosts: all
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"
  vars_files:
    - ./vars/install_vars_luminous_sda4.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - skyhook_basic

# copy helper files to build diretory.
- hosts: clients
  vars_files:
    - ./vars/install_vars_luminous_sda4.yml
  tasks:
    - name: "copy experiment helper scripts to build directory"
      copy:
        src: "{{ item }}"
        dest: "/mnt/{{ format_device }}/skyhook-ceph/build"
        mode: '0644'
      with_items:
        - ./files/validate_match.py
        - ./files/validate_time_assert.py
        - ./files/get_expected.sh

    - name: "copy experiment query files to build directory"
      copy:
        src: "{{ item }}"
        dest: "/mnt/{{ format_device }}/skyhook-ceph/build"
        mode: '0644'
      with_items:
        - ./exps/query_files/SELECT_ALL.sh
        - ./exps/query_files/PRED_QUERY.sh
        - ./exps/query_files/AGG_QUERY.sh
