# e.g. time ansible-playbook setup_playbook.yml -vvvv ;

---
# clone skyhook on each node, 
# run install-deps, 
# make the source code, 
# install the generated tabular so.
- hosts: all
  become: True
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"
  vars_files:
    - "{{ vars_file }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - skyhook_basic

# install postgres
- hosts: clients
  become: True
  tasks:
    - name: "install postgres on client0"
      shell: |
        sudo su -c "useradd postgres" ;
        sudo su -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >  /etc/apt/sources.list.d/pgdg.list' ;
        sudo su -c "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -" ;
        sudo su -c "sudo apt-get update" ;
        sudo su -c "yes | apt-get install postgresql-10" ;
        sudo su -c "yes | apt-get install postgresql-server-dev-10" ;
        sudo su -c "yes | apt-get install postgresql-contrib" ;
