# e.g. time ansible-playbook -K -b setup_playbook.yml -vvvv ;

---
# clone skyhook on each node, 
# run install-deps, 
# make the source code, 
# install the generated tabular so.
- hosts: all
  become: True
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"
  vars_files:
    - ./vars/install_vars_pdsw19_sda4.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - skyhook_basic

- name: run setup ceph cluster playbook from lib/ceph-deploy-ansible
  import_playbook: lib-transforms/ceph-deploy-ansible/ansible/playbook.yml

- hosts: clients
  become: True
  tasks:
    - name: "install postgres on client0"
      become: yes
      shell: |
        sudo su -c "useradd postgres" ;
        sudo su -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >  /etc/apt/sources.list.d/pgdg.list' ;
        sudo su -c "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -" ;
        sudo su -c "sudo apt-get update" ;
        sudo su -c "yes | apt-get install postgresql-10" ;
        sudo su -c "yes | apt-get install postgresql-server-dev-10" ;
        sudo su -c "yes | apt-get install postgresql-contrib" ;

# copy helper files to build diretory.
- hosts: clients
  become: True
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    this_user:  "{{ lookup('env','USER') }}"
  vars_files:
    - ./vars/install_vars_pdsw19_sda4.yml
  tasks:
    - name: "copy experiment helper scripts to build directory"
      copy:
        src: "{{ item }}"
        dest: "/mnt/{{ format_device }}/skyhookdm-ceph/build"
        mode: '0644'
      with_items:
        - ./files/validate_match.py
        - ./files/validate_time_assert.py
        - ./files/get_expected.sh
        - ./files/clear_objs.sh
        - ./files/scp_and_write_data.py
        - ./files/rsync_command.sh
        - ./files/rados_put.sh
        - ./files/rados-store-glob.sh
        - ./files/run-papertests-driver.sh
        - ./files/papertests-run-query-driver.sh
        - ./files/papertests-run-query-driver_randomsearch.sh
        - ./files/validate_xform_res.py
        - ./files/rados_put_parallel.py
        - ./files/parallel_merges.py
        - "/mnt/{{ format_device }}/skyhookdm-ceph/src/progly/katfiles/run_transform_tests.sh"
        - "/mnt/{{ format_device }}/skyhookdm-ceph/src/progly/katfiles/run_transform_tests_lineitem.sh"

    - name: "copy experiment query files to build directory"
      copy:
        src: "{{ item }}"
        dest: "/mnt/{{ format_device }}/skyhookdm-ceph/build"
        mode: '0644'
      with_items:
        - ./exps/query_files/SELECT_ALL.sh
        - ./exps/query_files/PRED_QUERY.sh
        - ./exps/query_files/AGG_QUERY.sh
