- name: "copy setup files"
  copy:
    src: "{{ item }}"
    dest: "{{ local_home }}"
    mode: '0644'
  with_items:
    - ./files/get_nodes.sh
    - ./files/cluster_setup_copy_ssh_keys.sh
    - ./files/format-device.sh

- name: "making the node list"
  shell: bash get_nodes.sh {{ num_osds }} ;

- name: "running ssh setup"
  shell: sh cluster_setup_copy_ssh_keys.sh ;

- name: "running format sda4"
  shell: sh format-device.sh {{ format_username }} {{ format_device }} ; 
  ignore_errors: yes

- name: "make cluster dir"
  file:
    path: "{{ local_home }}/cluster"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "install ceph-deploy"
  shell: |
    chmod -R '755' "{{ local_home }}/cluster" ;
    apt-get -f install ; 
    apt-get install -y python-virtualenv ; 
    cd "{{ local_home }}/cluster" ;
    virtualenv env ;
    env/bin/pip install ceph-deploy==1.5.38 ;

- name: "installing release on all hosts"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy install --release={{ release_name }} {{ item }} ;
  with_inventory_hostnames:
    - all

- name: "spinning up a new cluster"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy new client0 ;
  ignore_errors: yes

- name: "overwriting ceph.conf part0"
  copy: src="../../../ceph_conf/{{ ceph_conf }}"
        dest="{{ local_home }}/cluster"
        mode=preserve

- name: "overwriting ceph.conf part1"
  shell: |
    cd "{{ local_home }}/cluster" ;
    mv ceph.conf ceph.conf_default ;
    cat ceph.conf_default >> ceph.conf ;
    cat {{ ceph_conf }} >> ceph.conf ;
    chmod '777' ceph.conf ;

- name: "changing deploy log permissions"
  shell: |
    cd "{{ local_home }}/cluster" ;
    chmod '777' ceph-deploy-ceph.log ;

- name: "spinning up a new monitor"
  shell: |
    cd "{{ local_home }}/cluster" ;
    sudo chmod 766 *.keyring ;
    env/bin/ceph-deploy --overwrite-conf mon create client0 ;
    sudo chmod 766 *.keyring ;
    env/bin/ceph-deploy gatherkeys client0 ;
    sudo chmod 766 *.keyring ;

- name: "zap+create disks"
  vars:
     local_home: "{{ lookup('env','HOME') }}"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy osd create {{ item }}:{{ osd_device_path }} ;
    sudo chmod 766 *.keyring ;
  with_inventory_hostnames:
    - osds

- name: "spin up admin"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy admin client0 ;
    sudo chmod a+r /etc/ceph/ceph.client.admin.keyring ;
    sudo chmod 766 *.keyring ;

- name: "push configs to osds"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy config push {{ item }} ;
    sudo chmod 766 *.keyring ;
  with_inventory_hostnames:
    - osds

- name: "spin up mgr"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy mgr create client0 ;
    sudo chmod 766 *.keyring ;
